<?php
namespace zerist\create\factory;

abstract class Dialog{
    public abstract function createButton() : Button;

    public function render(){
        $btn = $this->createButton();
        echo get_class($btn);
        $btn->onClick();
        $btn->render();
    }
}

class WindowDialog extends Dialog{
    public function createButton() : Button
    {
        // TODO: Implement createButton() method.
        echo "create window dialog button" . PHP_EOL;
        return new WindowsButton();
    }

    public function render()
    {
        parent::render(); // TODO: Change the autogenerated stub
    }

}

class WebDialog extends Dialog{
    public function createButton() : Button
    {
        // TODO: Implement createButton() method.
        echo "create web dialog button" . PHP_EOL;
        return new HTMLButton();
    }

    public function render()
    {
        parent::render(); // TODO: Change the autogenerated stub
    }
}

interface Button {
    function render();
    function onClick();
}

class WindowsButton implements Button{
    public function onClick()
    {
        echo "windows button clicked" . PHP_EOL;
    }

    public function render()
    {
        echo "windows button render" . PHP_EOL;
    }
}

class HTMLButton implements Button{
    public function onClick()
    {
        // TODO: Implement onClick() method.
        echo "html button clicked" . PHP_EOL;
    }

    public function render()
    {
        // TODO: Implement render() method.
        echo "html button render" . PHP_EOL;
    }
}

class Application{
    public $dialog = null;
    public function initialize($btn_type) : Dialog
    {
        if($btn_type == 'html'){
            $this->dialog = new WebDialog();
        }elseif($btn_type == 'windows'){
            $this->dialog = new WindowDialog();
        }
    }

    public function run($btn_type){
        $this->initialize($btn_type);
        $this->dialog->render();
    }
}

$a = new Application();
$a->run('html');


